// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Datanode.proto

#include "proto/Datanode.pb.h"
#include "proto/Datanode.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Datanode {

static const char* BackupService_method_names[] = {
  "/Datanode.BackupService/copyBlock",
};

std::unique_ptr< BackupService::Stub> BackupService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BackupService::Stub> stub(new BackupService::Stub(channel, options));
  return stub;
}

BackupService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_copyBlock_(BackupService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::Datanode::copyBlockRequest>* BackupService::Stub::copyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::Datanode::copyBlockRequest>::Create(channel_.get(), rpcmethod_copyBlock_, context, response);
}

void BackupService::Stub::async::copyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::ClientWriteReactor< ::Datanode::copyBlockRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::Datanode::copyBlockRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_copyBlock_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>* BackupService::Stub::AsynccopyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::Datanode::copyBlockRequest>::Create(channel_.get(), cq, rpcmethod_copyBlock_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>* BackupService::Stub::PrepareAsynccopyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::Datanode::copyBlockRequest>::Create(channel_.get(), cq, rpcmethod_copyBlock_, context, response, false, nullptr);
}

BackupService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< BackupService::Service, ::Datanode::copyBlockRequest, ::Datanode::copyBlockResponse>(
          [](BackupService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::Datanode::copyBlockRequest>* reader,
             ::Datanode::copyBlockResponse* resp) {
               return service->copyBlock(ctx, reader, resp);
             }, this)));
}

BackupService::Service::~Service() {
}

::grpc::Status BackupService::Service::copyBlock(::grpc::ServerContext* context, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* reader, ::Datanode::copyBlockResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Datanode

