// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Datanode.proto
#ifndef GRPC_Datanode_2eproto__INCLUDED
#define GRPC_Datanode_2eproto__INCLUDED

#include "Datanode.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace Datanode {

class BackupService final {
 public:
  static constexpr char const* service_full_name() {
    return "Datanode.BackupService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::Datanode::copyBlockRequest>> copyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::Datanode::copyBlockRequest>>(copyBlockRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Datanode::copyBlockRequest>> AsynccopyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Datanode::copyBlockRequest>>(AsynccopyBlockRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Datanode::copyBlockRequest>> PrepareAsynccopyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Datanode::copyBlockRequest>>(PrepareAsynccopyBlockRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void copyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::ClientWriteReactor< ::Datanode::copyBlockRequest>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::Datanode::copyBlockRequest>* copyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::Datanode::copyBlockRequest>* AsynccopyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::Datanode::copyBlockRequest>* PrepareAsynccopyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::Datanode::copyBlockRequest>> copyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::Datanode::copyBlockRequest>>(copyBlockRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>> AsynccopyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>>(AsynccopyBlockRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>> PrepareAsynccopyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>>(PrepareAsynccopyBlockRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void copyBlock(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::ClientWriteReactor< ::Datanode::copyBlockRequest>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::Datanode::copyBlockRequest>* copyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response) override;
    ::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>* AsynccopyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::Datanode::copyBlockRequest>* PrepareAsynccopyBlockRaw(::grpc::ClientContext* context, ::Datanode::copyBlockResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_copyBlock_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status copyBlock(::grpc::ServerContext* context, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* reader, ::Datanode::copyBlockResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_copyBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_copyBlock() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_copyBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status copyBlock(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* /*reader*/, ::Datanode::copyBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcopyBlock(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::Datanode::copyBlockResponse, ::Datanode::copyBlockRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_copyBlock<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_copyBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_copyBlock() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::Datanode::copyBlockRequest, ::Datanode::copyBlockResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::Datanode::copyBlockResponse* response) { return this->copyBlock(context, response); }));
    }
    ~WithCallbackMethod_copyBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status copyBlock(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* /*reader*/, ::Datanode::copyBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::Datanode::copyBlockRequest>* copyBlock(
      ::grpc::CallbackServerContext* /*context*/, ::Datanode::copyBlockResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_copyBlock<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_copyBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_copyBlock() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_copyBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status copyBlock(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* /*reader*/, ::Datanode::copyBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_copyBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_copyBlock() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_copyBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status copyBlock(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* /*reader*/, ::Datanode::copyBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcopyBlock(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_copyBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_copyBlock() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->copyBlock(context, response); }));
    }
    ~WithRawCallbackMethod_copyBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status copyBlock(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Datanode::copyBlockRequest>* /*reader*/, ::Datanode::copyBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* copyBlock(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace Datanode


#endif  // GRPC_Datanode_2eproto__INCLUDED
