# 
# Created by cyt on 2023/9/22.
# 

# DataNode:
work_dir: "/mnt/d/test/rcv1/"
server_port: 8502
client_host: "localhost"
client_port: 8500
ipc_port: 8602
host:
  name: "lx-machine1"
  ip: "localhost"